### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by trylaarsdam**
Co-Authored-By: teamrobominable <teamrobominable@users.noreply.github.com>

### CODE REVIEW

**Review by teamrobominable — CHANGES_REQUESTED** [review]
Let's compromise for 50ms, as 10 would hog to many resources

**Review by teamrobominable — APPROVED** [review]
This pull request has been reviewed and approved by @teamrobominable.

**Comment by teamrobominable** [comment]
I'm going to close this due to no obvious gain from reducing system poll rate while increasing load.

**Comment by trylaarsdam** [comment]
Duplicate of #8 

_Closed and Locked_

**Pull request closed without merging**
